# Generated by Django 2.2 on 2022-01-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NA', max_length=255)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('date_time', models.DateTimeField(default='2022-01-01 00:00')),
                ('date', models.DateField(default='2022-01-01')),
                ('month', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('comments', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
