# Generated by Django 2.2 on 2022-01-02 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 2)),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 17, 15, 27, 400456)),
        ),
    ]
